// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testEmbed.proto

package sample.demo;

public final class TestEmbedContainer {
  private TestEmbedContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.InTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 DealTime = 1;</code>
     */
    boolean hasDealTime();
    /**
     * <code>optional int64 DealTime = 1;</code>
     */
    long getDealTime();

    /**
     * <code>optional string DealCode = 2;</code>
     */
    boolean hasDealCode();
    /**
     * <code>optional string DealCode = 2;</code>
     */
    java.lang.String getDealCode();
    /**
     * <code>optional string DealCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getDealCodeBytes();
  }
  /**
   * Protobuf type {@code demo.InTest}
   */
  public  static final class InTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.InTest)
      InTestOrBuilder {
    // Use InTest.newBuilder() to construct.
    private InTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InTest() {
      dealTime_ = 0L;
      dealCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dealTime_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dealCode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sample.demo.TestEmbedContainer.internal_static_demo_InTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sample.demo.TestEmbedContainer.internal_static_demo_InTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sample.demo.TestEmbedContainer.InTest.class, sample.demo.TestEmbedContainer.InTest.Builder.class);
    }

    private int bitField0_;
    public static final int DEALTIME_FIELD_NUMBER = 1;
    private long dealTime_;
    /**
     * <code>optional int64 DealTime = 1;</code>
     */
    public boolean hasDealTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 DealTime = 1;</code>
     */
    public long getDealTime() {
      return dealTime_;
    }

    public static final int DEALCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object dealCode_;
    /**
     * <code>optional string DealCode = 2;</code>
     */
    public boolean hasDealCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string DealCode = 2;</code>
     */
    public java.lang.String getDealCode() {
      java.lang.Object ref = dealCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dealCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DealCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDealCodeBytes() {
      java.lang.Object ref = dealCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dealCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, dealTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dealCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, dealTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dealCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sample.demo.TestEmbedContainer.InTest)) {
        return super.equals(obj);
      }
      sample.demo.TestEmbedContainer.InTest other = (sample.demo.TestEmbedContainer.InTest) obj;

      boolean result = true;
      result = result && (hasDealTime() == other.hasDealTime());
      if (hasDealTime()) {
        result = result && (getDealTime()
            == other.getDealTime());
      }
      result = result && (hasDealCode() == other.hasDealCode());
      if (hasDealCode()) {
        result = result && getDealCode()
            .equals(other.getDealCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDealTime()) {
        hash = (37 * hash) + DEALTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDealTime());
      }
      if (hasDealCode()) {
        hash = (37 * hash) + DEALCODE_FIELD_NUMBER;
        hash = (53 * hash) + getDealCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.InTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.InTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.InTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sample.demo.TestEmbedContainer.InTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.InTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.InTest)
        sample.demo.TestEmbedContainer.InTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sample.demo.TestEmbedContainer.internal_static_demo_InTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sample.demo.TestEmbedContainer.internal_static_demo_InTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sample.demo.TestEmbedContainer.InTest.class, sample.demo.TestEmbedContainer.InTest.Builder.class);
      }

      // Construct using sample.demo.TestEmbedContainer.InTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dealTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        dealCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sample.demo.TestEmbedContainer.internal_static_demo_InTest_descriptor;
      }

      public sample.demo.TestEmbedContainer.InTest getDefaultInstanceForType() {
        return sample.demo.TestEmbedContainer.InTest.getDefaultInstance();
      }

      public sample.demo.TestEmbedContainer.InTest build() {
        sample.demo.TestEmbedContainer.InTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sample.demo.TestEmbedContainer.InTest buildPartial() {
        sample.demo.TestEmbedContainer.InTest result = new sample.demo.TestEmbedContainer.InTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dealTime_ = dealTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dealCode_ = dealCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sample.demo.TestEmbedContainer.InTest) {
          return mergeFrom((sample.demo.TestEmbedContainer.InTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sample.demo.TestEmbedContainer.InTest other) {
        if (other == sample.demo.TestEmbedContainer.InTest.getDefaultInstance()) return this;
        if (other.hasDealTime()) {
          setDealTime(other.getDealTime());
        }
        if (other.hasDealCode()) {
          bitField0_ |= 0x00000002;
          dealCode_ = other.dealCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sample.demo.TestEmbedContainer.InTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sample.demo.TestEmbedContainer.InTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long dealTime_ ;
      /**
       * <code>optional int64 DealTime = 1;</code>
       */
      public boolean hasDealTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 DealTime = 1;</code>
       */
      public long getDealTime() {
        return dealTime_;
      }
      /**
       * <code>optional int64 DealTime = 1;</code>
       */
      public Builder setDealTime(long value) {
        bitField0_ |= 0x00000001;
        dealTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 DealTime = 1;</code>
       */
      public Builder clearDealTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dealTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object dealCode_ = "";
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public boolean hasDealCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public java.lang.String getDealCode() {
        java.lang.Object ref = dealCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dealCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDealCodeBytes() {
        java.lang.Object ref = dealCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dealCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public Builder setDealCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dealCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public Builder clearDealCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dealCode_ = getDefaultInstance().getDealCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DealCode = 2;</code>
       */
      public Builder setDealCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dealCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.InTest)
    }

    // @@protoc_insertion_point(class_scope:demo.InTest)
    private static final sample.demo.TestEmbedContainer.InTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sample.demo.TestEmbedContainer.InTest();
    }

    public static sample.demo.TestEmbedContainer.InTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InTest>
        PARSER = new com.google.protobuf.AbstractParser<InTest>() {
      public InTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InTest> getParserForType() {
      return PARSER;
    }

    public sample.demo.TestEmbedContainer.InTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 a = 1;</code>
     */
    boolean hasA();
    /**
     * <code>optional int32 a = 1;</code>
     */
    int getA();

    /**
     * <code>optional sint32 d = 2 [default = 20];</code>
     */
    boolean hasD();
    /**
     * <code>optional sint32 d = 2 [default = 20];</code>
     */
    int getD();

    /**
     * <code>optional string f = 4;</code>
     */
    boolean hasF();
    /**
     * <code>optional string f = 4;</code>
     */
    java.lang.String getF();
    /**
     * <code>optional string f = 4;</code>
     */
    com.google.protobuf.ByteString
        getFBytes();

    /**
     * <code>optional fixed32 e = 3;</code>
     */
    boolean hasE();
    /**
     * <code>optional fixed32 e = 3;</code>
     */
    int getE();

    /**
     * <code>repeated int32 g = 5;</code>
     */
    java.util.List<java.lang.Integer> getGList();
    /**
     * <code>repeated int32 g = 5;</code>
     */
    int getGCount();
    /**
     * <code>repeated int32 g = 5;</code>
     */
    int getG(int index);

    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getHList();
    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    int getHCount();
    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    int getH(int index);

    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    java.util.List<sample.demo.TestEmbedContainer.InTest> 
        getINtestList();
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    sample.demo.TestEmbedContainer.InTest getINtest(int index);
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    int getINtestCount();
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    java.util.List<? extends sample.demo.TestEmbedContainer.InTestOrBuilder> 
        getINtestOrBuilderList();
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    sample.demo.TestEmbedContainer.InTestOrBuilder getINtestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Test)
      TestOrBuilder {
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
      a_ = 0;
      d_ = 20;
      f_ = "";
      e_ = 0;
      g_ = java.util.Collections.emptyList();
      h_ = java.util.Collections.emptyList();
      iNtest_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              a_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              d_ = input.readSInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000008;
              e_ = input.readFixed32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              f_ = bs;
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                g_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              g_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                g_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                g_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                h_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              h_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                h_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                h_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                iNtest_ = new java.util.ArrayList<sample.demo.TestEmbedContainer.InTest>();
                mutable_bitField0_ |= 0x00000040;
              }
              iNtest_.add(
                  input.readMessage(sample.demo.TestEmbedContainer.InTest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          g_ = java.util.Collections.unmodifiableList(g_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          h_ = java.util.Collections.unmodifiableList(h_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          iNtest_ = java.util.Collections.unmodifiableList(iNtest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sample.demo.TestEmbedContainer.internal_static_demo_Test_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sample.demo.TestEmbedContainer.internal_static_demo_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sample.demo.TestEmbedContainer.Test.class, sample.demo.TestEmbedContainer.Test.Builder.class);
    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>optional int32 a = 1;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int D_FIELD_NUMBER = 2;
    private int d_;
    /**
     * <code>optional sint32 d = 2 [default = 20];</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint32 d = 2 [default = 20];</code>
     */
    public int getD() {
      return d_;
    }

    public static final int F_FIELD_NUMBER = 4;
    private volatile java.lang.Object f_;
    /**
     * <code>optional string f = 4;</code>
     */
    public boolean hasF() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string f = 4;</code>
     */
    public java.lang.String getF() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          f_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string f = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFBytes() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        f_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int E_FIELD_NUMBER = 3;
    private int e_;
    /**
     * <code>optional fixed32 e = 3;</code>
     */
    public boolean hasE() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional fixed32 e = 3;</code>
     */
    public int getE() {
      return e_;
    }

    public static final int G_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> g_;
    /**
     * <code>repeated int32 g = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getGList() {
      return g_;
    }
    /**
     * <code>repeated int32 g = 5;</code>
     */
    public int getGCount() {
      return g_.size();
    }
    /**
     * <code>repeated int32 g = 5;</code>
     */
    public int getG(int index) {
      return g_.get(index);
    }

    public static final int H_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> h_;
    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getHList() {
      return h_;
    }
    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    public int getHCount() {
      return h_.size();
    }
    /**
     * <code>repeated int32 h = 6 [packed = true];</code>
     */
    public int getH(int index) {
      return h_.get(index);
    }
    private int hMemoizedSerializedSize = -1;

    public static final int INTEST_FIELD_NUMBER = 7;
    private java.util.List<sample.demo.TestEmbedContainer.InTest> iNtest_;
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    public java.util.List<sample.demo.TestEmbedContainer.InTest> getINtestList() {
      return iNtest_;
    }
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    public java.util.List<? extends sample.demo.TestEmbedContainer.InTestOrBuilder> 
        getINtestOrBuilderList() {
      return iNtest_;
    }
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    public int getINtestCount() {
      return iNtest_.size();
    }
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    public sample.demo.TestEmbedContainer.InTest getINtest(int index) {
      return iNtest_.get(index);
    }
    /**
     * <code>repeated .demo.InTest iNtest = 7;</code>
     */
    public sample.demo.TestEmbedContainer.InTestOrBuilder getINtestOrBuilder(
        int index) {
      return iNtest_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, a_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, d_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed32(3, e_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, f_);
      }
      for (int i = 0; i < g_.size(); i++) {
        output.writeInt32(5, g_.get(i));
      }
      if (getHList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(hMemoizedSerializedSize);
      }
      for (int i = 0; i < h_.size(); i++) {
        output.writeInt32NoTag(h_.get(i));
      }
      for (int i = 0; i < iNtest_.size(); i++) {
        output.writeMessage(7, iNtest_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, d_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, e_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, f_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < g_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(g_.get(i));
        }
        size += dataSize;
        size += 1 * getGList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < h_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(h_.get(i));
        }
        size += dataSize;
        if (!getHList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        hMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < iNtest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, iNtest_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sample.demo.TestEmbedContainer.Test)) {
        return super.equals(obj);
      }
      sample.demo.TestEmbedContainer.Test other = (sample.demo.TestEmbedContainer.Test) obj;

      boolean result = true;
      result = result && (hasA() == other.hasA());
      if (hasA()) {
        result = result && (getA()
            == other.getA());
      }
      result = result && (hasD() == other.hasD());
      if (hasD()) {
        result = result && (getD()
            == other.getD());
      }
      result = result && (hasF() == other.hasF());
      if (hasF()) {
        result = result && getF()
            .equals(other.getF());
      }
      result = result && (hasE() == other.hasE());
      if (hasE()) {
        result = result && (getE()
            == other.getE());
      }
      result = result && getGList()
          .equals(other.getGList());
      result = result && getHList()
          .equals(other.getHList());
      result = result && getINtestList()
          .equals(other.getINtestList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA();
      }
      if (hasD()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + getD();
      }
      if (hasF()) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getF().hashCode();
      }
      if (hasE()) {
        hash = (37 * hash) + E_FIELD_NUMBER;
        hash = (53 * hash) + getE();
      }
      if (getGCount() > 0) {
        hash = (37 * hash) + G_FIELD_NUMBER;
        hash = (53 * hash) + getGList().hashCode();
      }
      if (getHCount() > 0) {
        hash = (37 * hash) + H_FIELD_NUMBER;
        hash = (53 * hash) + getHList().hashCode();
      }
      if (getINtestCount() > 0) {
        hash = (37 * hash) + INTEST_FIELD_NUMBER;
        hash = (53 * hash) + getINtestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sample.demo.TestEmbedContainer.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.demo.TestEmbedContainer.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sample.demo.TestEmbedContainer.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Test)
        sample.demo.TestEmbedContainer.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sample.demo.TestEmbedContainer.internal_static_demo_Test_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sample.demo.TestEmbedContainer.internal_static_demo_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sample.demo.TestEmbedContainer.Test.class, sample.demo.TestEmbedContainer.Test.Builder.class);
      }

      // Construct using sample.demo.TestEmbedContainer.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getINtestFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        a_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = 20;
        bitField0_ = (bitField0_ & ~0x00000002);
        f_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        e_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        g_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        h_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        if (iNtestBuilder_ == null) {
          iNtest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          iNtestBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sample.demo.TestEmbedContainer.internal_static_demo_Test_descriptor;
      }

      public sample.demo.TestEmbedContainer.Test getDefaultInstanceForType() {
        return sample.demo.TestEmbedContainer.Test.getDefaultInstance();
      }

      public sample.demo.TestEmbedContainer.Test build() {
        sample.demo.TestEmbedContainer.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sample.demo.TestEmbedContainer.Test buildPartial() {
        sample.demo.TestEmbedContainer.Test result = new sample.demo.TestEmbedContainer.Test(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.f_ = f_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.e_ = e_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          g_ = java.util.Collections.unmodifiableList(g_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.g_ = g_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          h_ = java.util.Collections.unmodifiableList(h_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.h_ = h_;
        if (iNtestBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            iNtest_ = java.util.Collections.unmodifiableList(iNtest_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.iNtest_ = iNtest_;
        } else {
          result.iNtest_ = iNtestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sample.demo.TestEmbedContainer.Test) {
          return mergeFrom((sample.demo.TestEmbedContainer.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sample.demo.TestEmbedContainer.Test other) {
        if (other == sample.demo.TestEmbedContainer.Test.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        if (other.hasD()) {
          setD(other.getD());
        }
        if (other.hasF()) {
          bitField0_ |= 0x00000004;
          f_ = other.f_;
          onChanged();
        }
        if (other.hasE()) {
          setE(other.getE());
        }
        if (!other.g_.isEmpty()) {
          if (g_.isEmpty()) {
            g_ = other.g_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureGIsMutable();
            g_.addAll(other.g_);
          }
          onChanged();
        }
        if (!other.h_.isEmpty()) {
          if (h_.isEmpty()) {
            h_ = other.h_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureHIsMutable();
            h_.addAll(other.h_);
          }
          onChanged();
        }
        if (iNtestBuilder_ == null) {
          if (!other.iNtest_.isEmpty()) {
            if (iNtest_.isEmpty()) {
              iNtest_ = other.iNtest_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureINtestIsMutable();
              iNtest_.addAll(other.iNtest_);
            }
            onChanged();
          }
        } else {
          if (!other.iNtest_.isEmpty()) {
            if (iNtestBuilder_.isEmpty()) {
              iNtestBuilder_.dispose();
              iNtestBuilder_ = null;
              iNtest_ = other.iNtest_;
              bitField0_ = (bitField0_ & ~0x00000040);
              iNtestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getINtestFieldBuilder() : null;
            } else {
              iNtestBuilder_.addAllMessages(other.iNtest_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sample.demo.TestEmbedContainer.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sample.demo.TestEmbedContainer.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int a_ ;
      /**
       * <code>optional int32 a = 1;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>optional int32 a = 1;</code>
       */
      public Builder setA(int value) {
        bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 a = 1;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }

      private int d_ = 20;
      /**
       * <code>optional sint32 d = 2 [default = 20];</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint32 d = 2 [default = 20];</code>
       */
      public int getD() {
        return d_;
      }
      /**
       * <code>optional sint32 d = 2 [default = 20];</code>
       */
      public Builder setD(int value) {
        bitField0_ |= 0x00000002;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 d = 2 [default = 20];</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000002);
        d_ = 20;
        onChanged();
        return this;
      }

      private java.lang.Object f_ = "";
      /**
       * <code>optional string f = 4;</code>
       */
      public boolean hasF() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string f = 4;</code>
       */
      public java.lang.String getF() {
        java.lang.Object ref = f_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            f_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string f = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFBytes() {
        java.lang.Object ref = f_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          f_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string f = 4;</code>
       */
      public Builder setF(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 4;</code>
       */
      public Builder clearF() {
        bitField0_ = (bitField0_ & ~0x00000004);
        f_ = getDefaultInstance().getF();
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 4;</code>
       */
      public Builder setFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        f_ = value;
        onChanged();
        return this;
      }

      private int e_ ;
      /**
       * <code>optional fixed32 e = 3;</code>
       */
      public boolean hasE() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional fixed32 e = 3;</code>
       */
      public int getE() {
        return e_;
      }
      /**
       * <code>optional fixed32 e = 3;</code>
       */
      public Builder setE(int value) {
        bitField0_ |= 0x00000008;
        e_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 e = 3;</code>
       */
      public Builder clearE() {
        bitField0_ = (bitField0_ & ~0x00000008);
        e_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> g_ = java.util.Collections.emptyList();
      private void ensureGIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          g_ = new java.util.ArrayList<java.lang.Integer>(g_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getGList() {
        return java.util.Collections.unmodifiableList(g_);
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public int getGCount() {
        return g_.size();
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public int getG(int index) {
        return g_.get(index);
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public Builder setG(
          int index, int value) {
        ensureGIsMutable();
        g_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public Builder addG(int value) {
        ensureGIsMutable();
        g_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public Builder addAllG(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, g_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 g = 5;</code>
       */
      public Builder clearG() {
        g_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> h_ = java.util.Collections.emptyList();
      private void ensureHIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          h_ = new java.util.ArrayList<java.lang.Integer>(h_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getHList() {
        return java.util.Collections.unmodifiableList(h_);
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public int getHCount() {
        return h_.size();
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public int getH(int index) {
        return h_.get(index);
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public Builder setH(
          int index, int value) {
        ensureHIsMutable();
        h_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public Builder addH(int value) {
        ensureHIsMutable();
        h_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public Builder addAllH(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureHIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, h_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 h = 6 [packed = true];</code>
       */
      public Builder clearH() {
        h_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private java.util.List<sample.demo.TestEmbedContainer.InTest> iNtest_ =
        java.util.Collections.emptyList();
      private void ensureINtestIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          iNtest_ = new java.util.ArrayList<sample.demo.TestEmbedContainer.InTest>(iNtest_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sample.demo.TestEmbedContainer.InTest, sample.demo.TestEmbedContainer.InTest.Builder, sample.demo.TestEmbedContainer.InTestOrBuilder> iNtestBuilder_;

      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public java.util.List<sample.demo.TestEmbedContainer.InTest> getINtestList() {
        if (iNtestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(iNtest_);
        } else {
          return iNtestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public int getINtestCount() {
        if (iNtestBuilder_ == null) {
          return iNtest_.size();
        } else {
          return iNtestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public sample.demo.TestEmbedContainer.InTest getINtest(int index) {
        if (iNtestBuilder_ == null) {
          return iNtest_.get(index);
        } else {
          return iNtestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder setINtest(
          int index, sample.demo.TestEmbedContainer.InTest value) {
        if (iNtestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureINtestIsMutable();
          iNtest_.set(index, value);
          onChanged();
        } else {
          iNtestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder setINtest(
          int index, sample.demo.TestEmbedContainer.InTest.Builder builderForValue) {
        if (iNtestBuilder_ == null) {
          ensureINtestIsMutable();
          iNtest_.set(index, builderForValue.build());
          onChanged();
        } else {
          iNtestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder addINtest(sample.demo.TestEmbedContainer.InTest value) {
        if (iNtestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureINtestIsMutable();
          iNtest_.add(value);
          onChanged();
        } else {
          iNtestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder addINtest(
          int index, sample.demo.TestEmbedContainer.InTest value) {
        if (iNtestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureINtestIsMutable();
          iNtest_.add(index, value);
          onChanged();
        } else {
          iNtestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder addINtest(
          sample.demo.TestEmbedContainer.InTest.Builder builderForValue) {
        if (iNtestBuilder_ == null) {
          ensureINtestIsMutable();
          iNtest_.add(builderForValue.build());
          onChanged();
        } else {
          iNtestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder addINtest(
          int index, sample.demo.TestEmbedContainer.InTest.Builder builderForValue) {
        if (iNtestBuilder_ == null) {
          ensureINtestIsMutable();
          iNtest_.add(index, builderForValue.build());
          onChanged();
        } else {
          iNtestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder addAllINtest(
          java.lang.Iterable<? extends sample.demo.TestEmbedContainer.InTest> values) {
        if (iNtestBuilder_ == null) {
          ensureINtestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, iNtest_);
          onChanged();
        } else {
          iNtestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder clearINtest() {
        if (iNtestBuilder_ == null) {
          iNtest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          iNtestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public Builder removeINtest(int index) {
        if (iNtestBuilder_ == null) {
          ensureINtestIsMutable();
          iNtest_.remove(index);
          onChanged();
        } else {
          iNtestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public sample.demo.TestEmbedContainer.InTest.Builder getINtestBuilder(
          int index) {
        return getINtestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public sample.demo.TestEmbedContainer.InTestOrBuilder getINtestOrBuilder(
          int index) {
        if (iNtestBuilder_ == null) {
          return iNtest_.get(index);  } else {
          return iNtestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public java.util.List<? extends sample.demo.TestEmbedContainer.InTestOrBuilder> 
           getINtestOrBuilderList() {
        if (iNtestBuilder_ != null) {
          return iNtestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(iNtest_);
        }
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public sample.demo.TestEmbedContainer.InTest.Builder addINtestBuilder() {
        return getINtestFieldBuilder().addBuilder(
            sample.demo.TestEmbedContainer.InTest.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public sample.demo.TestEmbedContainer.InTest.Builder addINtestBuilder(
          int index) {
        return getINtestFieldBuilder().addBuilder(
            index, sample.demo.TestEmbedContainer.InTest.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.InTest iNtest = 7;</code>
       */
      public java.util.List<sample.demo.TestEmbedContainer.InTest.Builder> 
           getINtestBuilderList() {
        return getINtestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sample.demo.TestEmbedContainer.InTest, sample.demo.TestEmbedContainer.InTest.Builder, sample.demo.TestEmbedContainer.InTestOrBuilder> 
          getINtestFieldBuilder() {
        if (iNtestBuilder_ == null) {
          iNtestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sample.demo.TestEmbedContainer.InTest, sample.demo.TestEmbedContainer.InTest.Builder, sample.demo.TestEmbedContainer.InTestOrBuilder>(
                  iNtest_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          iNtest_ = null;
        }
        return iNtestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Test)
    }

    // @@protoc_insertion_point(class_scope:demo.Test)
    private static final sample.demo.TestEmbedContainer.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sample.demo.TestEmbedContainer.Test();
    }

    public static sample.demo.TestEmbedContainer.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    public sample.demo.TestEmbedContainer.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_InTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_InTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017testEmbed.proto\022\004demo\",\n\006InTest\022\020\n\010Dea" +
      "lTime\030\001 \001(\003\022\020\n\010DealCode\030\002 \001(\t\"n\n\004Test\022\t\n" +
      "\001a\030\001 \001(\005\022\r\n\001d\030\002 \001(\021:\00220\022\t\n\001f\030\004 \001(\t\022\t\n\001e\030" +
      "\003 \001(\007\022\t\n\001g\030\005 \003(\005\022\r\n\001h\030\006 \003(\005B\002\020\001\022\034\n\006iNtes" +
      "t\030\007 \003(\0132\014.demo.InTestB!\n\013sample.demoB\022Te" +
      "stEmbedContainer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_InTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_InTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_InTest_descriptor,
        new java.lang.String[] { "DealTime", "DealCode", });
    internal_static_demo_Test_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Test_descriptor,
        new java.lang.String[] { "A", "D", "F", "E", "G", "H", "INtest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
